src/Entity/Agents.php
<?php

namespace App\Entity;

use App\Repository\AgentsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AgentsRepository::class)
 */
class Agents
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $PrenomAutres;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Mail;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Matricule;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $commentaire;

    /**
     * @ORM\ManyToOne(targetEntity=Secteurs::class, inversedBy="agents")
     */
    private $Secteur;

    /**
     * @ORM\ManyToOne(targetEntity=Fonctions::class, inversedBy="agents")
     */
    private $Fonction;

    /**
     * @ORM\OneToMany(targetEntity=Comptes::class, mappedBy="agents")
     */
    private $Comptes;

    /**
     * @ORM\OneToMany(targetEntity=Contrats::class, mappedBy="agents")

     */
    private $Contrats;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $Softs = [];

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $EnvoiMail;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $EnvoiSms;

    public function __construct()
    {
        $this->Comptes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getPrenomAutres(): ?string
    {
        return $this->PrenomAutres;
    }

    public function setPrenomAutres(?string $PrenomAutres): self
    {
        $this->PrenomAutres = $PrenomAutres;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->Mail;
    }

    public function setMail(?string $Mail): self
    {
        $this->Mail = $Mail;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(?string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getMatricule(): ?string
    {
        return $this->Matricule;
    }

    public function setMatricule(?string $Matricule): self
    {
        $this->Matricule = $Matricule;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getSecteur(): ?Secteurs
    {
        return $this->Secteur;
    }

    public function setSecteur(?Secteurs $Secteur): self
    {
        $this->Secteur = $Secteur;

        return $this;
    }

    public function getFonction(): ?Fonctions
    {
        return $this->Fonction;
    }

    public function setFonction(?Fonctions $Fonction): self
    {
        $this->Fonction = $Fonction;

        return $this;
    }

    /**
     * @return Collection|Comptes[]
     */
    public function getComptes(): Collection
    {
        return $this->Comptes;
    }

    public function addCompte(Comptes $compte): self
    {
        if (!$this->Comptes->contains($compte)) {
            $this->Comptes[] = $compte;
            $compte->setAgents($this);
        }

        return $this;
    }

    public function removeCompte(Comptes $compte): self
    {
        if ($this->Comptes->removeElement($compte)) {
            // set the owning side to null (unless already changed)
            if ($compte->getAgents() === $this) {
                $compte->setAgents(null);
            }
        }

        return $this;
    }




    /**
     * @return Collection|Contrats[]
     */
    public function getContrats(): Collection
    {
        return $this->Contrats;
    }

    public function addContrat(Contrats $contrat): self
    {
        if (!$this->Contrats->contains($contrat)) {
            $this->Contrats[] = $contrat;
            $contrat->setAgents($this);
        }

        return $this;
    }

    public function removeContrat(Contrats $contrat): self
    {
        if ($this->Contrats->removeElement($contrat)) {
            // set the owning side to null (unless already changed)
            if ($contrat->getAgents() === $this) {
                $contrat->setAgents(null);
            }
        }

        return $this;
    }








    public function getSofts(): ?array
    {
        return $this->Softs;
    }

    public function setSofts(?array $Softs): self
    {
        $this->Softs = $Softs;

        return $this;
    }

    public function getEnvoiMail(): ?bool
    {
        return $this->EnvoiMail;
    }

    public function setEnvoiMail(?bool $EnvoiMail): self
    {
        $this->EnvoiMail = $EnvoiMail;

        return $this;
    }

    public function getEnvoiSms(): ?bool
    {
        return $this->EnvoiSms;
    }

    public function setEnvoiSms(?bool $EnvoiSms): self
    {
        $this->EnvoiSms = $EnvoiSms;

        return $this;
    }
}

src/Entity/Contrats.php
<?php

namespace App\Entity;

use App\Repository\ContratsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContratsRepository::class)
 */
class Contrats
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $DateDebut;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $DateFin;



    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $Actif;

    /**
     * @ORM\ManyToOne(targetEntity=Agents::class, inversedBy="Contrats")
     */
    private $agents;

    /**
     * @ORM\ManyToOne(targetEntity=TypesContrat::class, inversedBy="contrats")
     * @ORM\JoinColumn(nullable=false)
     */
    private $TypeContrat;

    /**
     * @ORM\Column(type="integer")
     */
    private $preuve;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $createur;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $DateAjout;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $dernierContrat;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(?\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(?\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }



    public function getActif(): ?bool
    {
        return $this->Actif;
    }

    public function setActif(?bool $Actif): self
    {
        $this->Actif = $Actif;

        return $this;
    }

    public function getAgents(): ?Agents
    {
        return $this->agents;
    }

    public function setAgents(?Agents $agents): self
    {
        $this->agents = $agents;

        return $this;
    }

    public function getTypeContrat(): ?TypesContrat
    {
        return $this->TypeContrat;
    }

    public function setTypeContrat(?TypesContrat $TypeContrat): self
    {
        $this->TypeContrat = $TypeContrat;

        return $this;
    }

    public function getPreuve(): ?int
    {
        return $this->preuve;
    }

    public function setPreuve(int $preuve): self
    {
        $this->preuve = $preuve;

        return $this;
    }

    public function getCreateur(): ?string
    {
        return $this->createur;
    }

    public function setCreateur(?string $createur): self
    {
        $this->createur = $createur;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->DateAjout;
    }

    public function setDateAjout(?\DateTimeInterface $DateAjout): self
    {
        $this->DateAjout = $DateAjout;

        return $this;
    }

    public function getDernierContrat(): ?bool
    {
        return $this->dernierContrat;
    }

    public function setDernierContrat(?bool $dernierContrat): self
    {
        $this->dernierContrat = $dernierContrat;

        return $this;
    }


}

templates/agents/addAgent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les agents{% endblock %}

{% block body %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <h4>Ajout d'un agent</h4>
            </div>
        </div>

            {{ form(form) }}
        {% endblock %}
    </div>
{% endblock %}

templates/agents/addAgentOK.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les agents{% endblock %}

{% block body %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <h1>Validé</h1>
            </div>
        </div>

        <h1>Validé</h1>
            {{ form(form) }}
        <a href={{ path ('agents')}}>Retour a la liste</a>
        {% endblock %}
    </div>
{% endblock %}

templates/agents/addCompte.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les agents{% endblock %}

{% block body %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <h4>Ajout d'un compte pour {{ Agents.nom }} {{ Agents.prenom }}</h4>
            </div>
        </div>

            {{ form(form) }}
        {% endblock %}
    </div>
{% endblock %}

templates/agents/addContrat.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les agents{% endblock %}

{% block body %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <h4>Ajout d'un compte pour  {{ Agents.nom }} {{ Agents.prenom }}</h4>
            </div>
        </div>

            {{ form(form) }}
        {% endblock %}
    </div>
{% endblock %}

templates/agents/adez.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les agents{% endblock %}

{% block body %}
    {% block content %}

    <div class="container">
    <h1 class="mt-5">Les Agents  <a class="btn btn-success" href='/agents/addAgent'><i class="fa-solid fa-plus"></i>  Ajouter</a></h1>

    <div class="row">

    <div class="container">
            <table class="table" id="example">
                <thead>
                    <tr>
                      <th>
                          Compte/Login
                      </th>
                      <th>
                          Softs
                      </th>
                      <th>
                          Nom
                      </th>
                        <th>
                            Prénom
                        </th>
                        <th>
                            Prénom autres
                        </th>
                        <th>
                            Secteur
                        </th>
                        <th>
                            Fonction
                        </th>
                        <th>
                            Matricule
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

                    {% for Agents in Agents %}
                      {% for Comptes in Agents.Comptes %}
                        {% if  Comptes.actif == '1' %}
                        {% for Contrats in Agents.Contrats %}
                          {% if  Contrats.datefin|date('Y-m-d')  <  "now"|date("Y-m-d") and Contrats.dernierContrat == '1' %}
                        <tr>
                          <th>
                              {{ Comptes.login }}
                          </th>
                          <th>
                            {% for Softs in Comptes.Softs %}
                              {% if loop.last %}
                                  {{ Softs.SoftLibelle }}
                                  {% else %}
                                      {{ Softs.SoftLibelle }} -
                                  {% endif %}
                                {% endfor %}
                          </th>

                            <th>
                                {{ Agents.Nom }}
                            </th>
                            <td>
                                {{ Agents.prenom }}
                            </td>
                            <td>
                                {{ Agents.PrenomAutres }}
                            </td>
                            <td>
                                {{ Agents.Secteur.SecteurLibelle }}
                            </td>
                            <td>
                                {{ Agents.Fonction.FonctionLibelle }}
                            </td>
                            <td>
                                {{ Agents.Matricule }}
                            </td>
                            <td><a href={{ path('agent', {'id': Agents.id}) }}><i class="fa-solid fa-eye"></i></a>
                            <a href={{ path('editAgent', {'id': Agents.id}) }}><i class="fa-solid fa-pen-to-square"></i></a>
                            <a href={{ path('dezCompte',{'id' : Comptes.id})}}><i class="fa-solid fa-circle-minus"></i></a>
                    </td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
                        {% endfor %}
                    {% endfor %}

                </tbody>
            </table>
            </div>
            <div class="row" style="margin-top:20px;Margin-right:0px;">
            <div class="text-end">
            <a class="btn btn-success" href='/agents/addAgent'><i class="fa-solid fa-plus"></i> Ajouter</a>
            </div></div>
        </div>
        {% endblock %}
    {% endblock %}
    {% block script %}

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/cesiumjs/1.78/Build/Cesium/Cesium.js"></script>
<script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js" integrity="sha256-xH4q8N0pEzrZMaRmd7gQVcTZiFei+HfRTBPJ1OGXC0k=" crossorigin="anonymous"></script>

<script>

$(document).ready(function () {
    $('#example').DataTable();
});

</script>
{% endblock %}

templates/agents/detail.html.twig

{% extends 'base.html.twig' %}
{% block title %}
Les agents
{% endblock %}
{% block script %}
{% endblock %}
{% block body %}
{% block content %}
<div class='container' style="padding-left: 0px;">
  <div class="card"  style="width: 25rem; margin-top: 25px; ">
    <div class="card-header">
      <div class="row">
        <div class="col">
          <h5 class="card-title transform1">
            {{ Agents.Nom }}
            {{ Agents.prenom }}
          </h5>
        </div>
        <div class="col text-end">
          <a href={{ path('editAgent', {'id': Agents.id} )  }}>
            <i class="fa-solid fa-pen-to-square "></i>
          </a>
          <a id="dtogg" data-tooltip="Afficher le detail"><i class="fa-solid fa-circle-info"></i></a>
        </div>
      </div>
      <div class="row">
        {{ Agents.Fonction.FonctionLibelle }} => {{ Agents.Secteur.Etablissements.EtabLibelle }} // {{ Agents.Secteur.SecteurLibelle}}
      </div>
    </div>
    <div class="card-body" id="ddetail" style="display:none">
      <p class="card-text">
        Matricule :
        {{ Agents.Matricule }}
      </p>
      <p class="card-text">
        Autres prenom(s) :
        {{ Agents.PrenomAutres }}
      </p>
      {% if Agents.EnvoiMail == 1 %}
      <p class="card-text">
        Mail :
        {{ Agents.Mail }}
      </p>
      {% else %}
      <p class="card-text">
        Mail :
        <a data-tooltip="Envoi de mail non autorisé"><i class="fa-solid fa-triangle-exclamation"></i><s>{{ Agents.Mail }}</s></a>
      </p>
      {% endif %}
      {% if Agents.EnvoiSms == 1 %}
      <p class="card-text">
        Téléphone :
        {{ Agents.Tel }}
      </p>
      {% else %}
      <p class="card-text">
        Téléphone :
        <a data-tooltip="Envoi de Sms non autorisé"><i class="fa-solid fa-triangle-exclamation"></i><s>{{ Agents.Tel }}</s></a>
      </p>
      {% endif %}
    </div>
  </div>

</div>
<div class="container">
  <h1>
    Comptes
    <a class="btn btn-success" href={{ path('addcompteagent', {'id': Agents.id } )  }}>
      <i class="fa-solid fa-plus"></i>
    </a>
  </h1>
  <div class="row">
    {% for Comptes in Comptes %}

    <div class='card'>
      <div class='card-header' style="max-height:80px">
        <div class='row gx-0'>
          <div class="col-4">
            <h4>{{ loop.index }}
            {% if Comptes.Actif == 1 %}
            <a  data-tooltip="Comtpe Actif"><i class="fa-solid fa-user-tag text-success"> : </i></a>
            {% else %}
            <a data-tooltip="Comtpe Inctif"><i class="fa-solid fa-user-slash text-warning"> : </i></a>
              {% endif %} {{ Comptes.login }}
              <a class="text-right" data-tooltip="Editer le compte" href={{ path('editcompteagent', {'id': Agents.id, 'idcompte': Comptes.id } )  }}>
                <i class="fa-solid fa-pen-to-square "></i>
              </a>
              {% if (Comptes.Pwd is not null) and (Comptes.Pwd != 'NULL') %}
              <a id="togg{{loop.index}}" data-tooltip="Afficher le mot de passe" ><i class="fa-solid fa-eye" id="eye{{loop.index}}"></i></a>
              {% else %}
              <a data-tooltip="Générer un mot de passe" href={{ path('newPwd', {'id': Agents.id, 'idcompte': Comptes.id } )  }} style="color:inherit;"><i class="fa-solid fa-rotate"></i></a>
              {% endif %}
              <a id="btogg{{loop.index}}" data-tooltip="Afficher le detail"><i class="fa-solid fa-circle-info"></i></a>
              <span id="pwd{{loop.index}}" style="display:none"> {{ Comptes.pwd }}</span>
            </h4>
          </div>
          <div class="col"><ul>
            {% for Softs in Comptes.Softs %}
            {% if loop.last %}
                {{ Softs.SoftLibelle }}
                {% else %}
                    {{ Softs.SoftLibelle }} -
                    {% endif %}
            {% endfor %}

          </div>
          <div class="col-3">
            <div class="row">
              <div class="col">
                <a class="btn btn-primary btn-sm" data-tooltip="Générer enveloppe" href="/comptes/{{ Comptes.id }}/enveloppe">
                  <i class="fa-solid fa-envelope"></i>
                </a>

                {% if (Comptes.Pwd is not null) and (Comptes.Pwd != 'NULL') %}

                <a class="btn btn-primary btn-sm" data-tooltip="Générer courrier" href="/comptes/{{ Comptes.id }}/courrier">
                  <i class="fa-solid fa-envelope-open-text"></i>
                </a>
                {% endif %}
                {% if Agents.Mail is not null %}
                {% if Agents.EnvoiMail == 1 %}
                <a class="btn btn-info btn-sm" data-tooltip="Envoyer login par email" href={{ path('sendEmailInit', {'id': Agents.id, 'idcompte': Comptes.id } )  }}>
                  <i class="fa-solid fa-user"> <i class="fa-solid fa-at"></i></i>
                </a>
                {% if (Comptes.Pwd is not null) and (Comptes.Pwd != 'NULL') %}
                <a class="btn btn-info btn-sm" data-tooltip="Envoyer mot de passe par email" href={{ path('sendEmailPwdInit', {'id': Agents.id, 'idcompte': Comptes.id } )  }}>
                  <i class="fa-solid fa-key"> <i class="fa-solid fa-at"></i></i>
                </a>
                {% endif %}
                {% else %}
                <a class="btn btn-secondary btn-sm" data-tooltip="Envoi par mail non autorisé" disabled>
                  <i class="fa-solid fa-user"> <i class="fa-solid fa-at"></i></i>
                </a>
                <a class="btn btn-secondary btn-sm" data-tooltip="Envoi par mail non autorisé" disabled>
                  <i class="fa-solid fa-key"> <i class="fa-solid fa-at"></i></i>
                </a>
                {% endif %}
                {% endif %}
                {% if Agents.Tel is not null %}
                {% if Agents.EnvoiSMS == 1 %}
                <a class="btn btn-primary btn-sm" data-tooltip="Envoyer login par SMS" href={{ path('sendSmsInit', {'id': Agents.id, 'idcompte': Comptes.id } )  }}>
                  <i class="fa-solid fa-user"> <i class="fa-solid fa-comment-sms"></i></i>
                </a>
                {% if (Comptes.Pwd is not null) and (Comptes.Pwd != 'NULL') %}
                <a class="btn btn-primary btn-sm" data-tooltip="Envoyer mot de passe par SMS" href={{ path('sendSmsInitPwd', {'id': Agents.id, 'idcompte': Comptes.id } )  }}>
                  <i class="fa-solid fa-key"> <i class="fa-solid fa-comment-sms"></i></i>
                {% endif %}
                </a>
                {% else %}
                <a class="btn btn-secondary btn-sm" data-tooltip="Envoi par SMS non autorisé" disabled>
                  <i class="fa-solid fa-user"> <i class="fa-solid fa-comment-sms"></i></i>
                </a>
                <a class="btn btn-secondary btn-sm" data-tooltip="Envoi par SMS non autorisé" disabled>
                  <i class="fa-solid fa-key"> <i class="fa-solid fa-comment-sms"></i></i>
                </a>
                {% endif %}
                {% endif %}
              </div>
            </div>
          </div>
          <div class="col-2" style="text-align:end;">
            Crée par : {{ Comptes.Createur}} le {{ Comptes.DateCreation|date('d-m-Y') }} <br>
            Modifié par : {{ Comptes.Modificateur }} le {{ Comptes.DateModif|date('d-m-Y') }}

          </div>
        </div>
      </div>
      <div class="row">
        <span id="adetail{{loop.index}}"  style="display:none">
          {% for Softs in Comptes.Softs %}
          <div class='card-body'>
            <div class="row">
              <div class="col-1">
                <h5 class="card-title">
                  {{ Softs.SoftLibelle }}
                </h5>
              </div>
              <div class="col">
                {% if Agents.Mail is not null %}
                {% if Agents.EnvoiMail == 1 %}
                <a class="btn btn-info btn-sm" data-tooltip="Envoyer login par email" href={{ path('sendEmail', {'id': Agents.id, 'idcompte': Comptes.id, 'idsoft': Softs.id } )  }}>
                  <i class="fa-solid fa-user"> <i class="fa-solid fa-at"></i></i>
                </a>
                {% if (Comptes.Pwd is not null) and (Comptes.Pwd != 'NULL') %}

                <a class="btn btn-info btn-sm" data-tooltip="Envoyer mot de passe par email" href={{ path('sendEmailPwd', {'id': Agents.id, 'idcompte': Comptes.id, 'idsoft': Softs.id } )  }}>
                  <i class="fa-solid fa-key"> <i class="fa-solid fa-at"></i></i>
                </a>
                {% endif %}
                {% else %}
                <a class="btn btn-secondary btn-sm" data-tooltip="Envoi par mail non autorisé" disabled>
                  <i class="fa-solid fa-user"> <i class="fa-solid fa-at"></i></i>
                </a>
                <a class="btn btn-secondary btn-sm" data-tooltip="Envoi par mail non autorisé" disabled>
                  <i class="fa-solid fa-key"> <i class="fa-solid fa-at"></i></i>
                </a>
                {% endif %}
                {% endif %}
                {% if Agents.Tel is not null %}
                {% if Agents.EnvoiSms == 1 %}
                <a class="btn btn-primary btn-sm" data-tooltip="Envoyer login par SMS" href={{ path('sendSms', {'id': Agents.id, 'idcompte': Comptes.id, 'idsoft': Softs.id } )  }}>
                  <i class="fa-solid fa-user"> <i class="fa-solid fa-comment-sms"></i></i>
                </a>
                {% if (Comptes.Pwd is not null) and (Comptes.Pwd != 'NULL') %}

                <a class="btn btn-primary btn-sm" data-tooltip="Envoyer mot de passe par SMS" href={{ path('sendSmsPwd', {'id': Agents.id, 'idcompte': Comptes.id, 'idsoft': Softs.id } )  }}>
                  <i class="fa-solid fa-key"> <i class="fa-solid fa-comment-sms"></i></i>
                </a>
                {% endif %}
                {% else %}
                <a class="btn btn-secondary btn-sm" data-tooltip="Envoi par SMS non autorisé" disabled>
                  <i class="fa-solid fa-user"> <i class="fa-solid fa-comment-sms"></i></i>
                </a>
                <a class="btn btn-secondary btn-sm" data-tooltip="Envoi par SMS non autorisé" disabled>
                  <i class="fa-solid fa-key"> <i class="fa-solid fa-comment-sms"></i></i>
                </a>
                {% endif %}
                {% endif %}
              </div>
            </div>
          </div>

          {% endfor %}
        </span>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
</div>
<div class="container">
  <h1>
    Contrats
    <a class="btn btn-success" href={{ path('addcontratagent', {'id': Agents.id } )  }}>
      <i class="fa-solid fa-plus"></i>
    </a>
  </h1>
  <div class="row">
    {% for Contrats in Contrats %}
    <div class='col-3'>
      <div class="card" style="width: 20rem; margin-left=15px">
        <div class="card-header">
          <div class="row">
            {% if Contrats.dernierContrat == 1 %}
            <h4 class="card-title">
              <span class="text-success" data-tooltip="Dernier contrat">

              {{ loop.index }}
              Contrat
              {{ Contrats.id }}</span>
              {% else %}
              <h4 class="card-title">
                {{ loop.index }}

              Contrat
              {{ Contrats.id }}
              {% endif %}
              <a  href={{ path('editcontratagent', {'id': Agents.id, 'idcontrat': Contrats.id } )  }} data-tooltip="Editer contrat">
                <i class="fa-solid fa-pen-to-square "></i>
              </a>
              <a id="ctogg{{loop.index}}" data-tooltip="Afficher le detail"><i class="fa-solid fa-circle-info"></i></a>
            </h4>
          </div>
        </div>
        <div class="card-body" id="cdetail{{loop.index}}" style="display:none">
          <h6 class="card-subtitle mb-2">
            {{ Contrats.TypeContrat.TypeContratLibelle }}
          </h6>
          <p class="card-text">
            Date de début :
            {{ Contrats.datedebut|date('d-m-Y') }}
          </p>
          <p class="card-text">
            Date de fin :
            {{ Contrats.datefin|date('d-m-Y') }}
          </p>
          <a class="btn btn-outline-primary btn-sm" href='http://intranet/projeqtor/view/main.php?directAccess=true&objectClass=Ticket&objectId={{ Contrats.preuve }}' target='_blank'>
            Voir la preuve
          </a>
        </div>
        <div class="card-footer" id="bdetail{{loop.index}}" style="display:none">
          Ajouté par {{ Contrats.Createur }} le {{ Contrats.DateAjout|date('d-m-Y') }}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <div>
  </div>
</div>
{% endblock %}
{% endblock %}
{% block scripts %}
<script>
</script>
{% endblock %}

templates/agents/editCompteAgent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les agents{% endblock %}

{% block body %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <h4>Edition du {{ Comptes.Login }} compte pour {{ Agents.nom }} {{ Agents.prenom }}</h4>
            </div>
        </div>

            {{ form(form) }}
        {% endblock %}
    </div>
{% endblock %}

templates/agents/editContrat.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les agents{% endblock %}

{% block body %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <h4>Edition du contrat {{ Contrats.id }} pour {{ Agents.nom }} {{ Agents.prenom }}</h4>
            </div>
        </div>

            {{ form(form) }}
        {% endblock %}
    </div>
{% endblock %}